# Generated by Django 3.1.5 on 2021-01-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bola2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero del pedido')),
                ('fecha', models.DateField(verbose_name='Fecha del pedido')),
                ('estado', models.CharField(choices=[('E', 'Entregado'), ('P', 'Pendiente')], max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Telefono',
            field=models.CharField(max_length=9, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='colores',
            field=models.CharField(choices=[('1', 'Rojo'), ('2', 'Negro'), ('3', 'Azul'), ('4', 'Blanco')], max_length=1, verbose_name='Colores'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(max_length=10, verbose_name='Tamaño'),
        ),
    ]
