# Generated by Django 3.1.5 on 2021-01-24 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tamaño', models.CharField(max_length=10, verbose_name='Tamaño')),
                ('colores', models.CharField(choices=[('1', 'Negro'), ('2', 'Azul metálico'), ('3', 'Rasta'), ('4', 'Silver'), ('5', 'Gold')], max_length=1, verbose_name='Color')),
                ('precio', models.CharField(max_length=10, verbose_name='Precio')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero del pedido')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del pedido')),
                ('estado', models.CharField(choices=[('E', 'Envío'), ('R', 'Retiro en tienda')], max_length=1, verbose_name='Entrega')),
                ('entrega', models.DateField(verbose_name='Fecha de entrega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bolados.producto', verbose_name='Producto')),
            ],
        ),
    ]
