# Generated by Django 3.1.5 on 2021-01-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolados', '0002_pedido_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
    ]
