# Generated by Django 3.1.5 on 2021-01-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolados', '0003_auto_20210125_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del pedido'),
        ),
    ]
